$schema: https://railway.app/railway.schema.json
build:
  builder: nixpacks
  buildCommand: npm install && npm run build
  watchPatterns:
    - "src/**"
    - "public/**"
deploy:
  startCommand: npx serve -s build -l $PORT
  healthcheckTimeout: 100
  restartPolicyType: always
